---
title: "STP598sta: Spatiotemporal Analysis"
subtitle: "Homework 4"
author: "Name: Your name; NetID: Your ID"
date: "Due 11:59pm Sunday November 6, 2022"
output:
  pdf_document: default
  # html_document: default
  # word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
options(width = 1000)
```

## Question 1

For the non-causal stationary process
\begin{equation*}
x_t = \phi x_{t-1} + w_t, \quad |\phi|>1
\end{equation*}
and $w_t\overset{iid}{\sim} N(0, \sigma^2_w)$.
What is the autocovariance? ACF?

## Question 2

For the AR(2) series $x_t+1.6x_{t-1}+0.64 x_{t-2}=w_t$, use the difference equation (ref pages 19-25 of lecture 8, or the resutls of Example 3.10 of TSA book) to find the ACF $\rho(h), h=0,1,\cdots$; solve for the constants in the ACF using the initial conditions. Then plot the ACF values to lag 10 (use `ARMAacf` as a check on your answers).

## Question 3

Generate $n=100$ observations from each of the three models: (a) AR(1), (b) MAR(1) and (c) ARMA(1,1) with $\phi=0.6$ and $\theta=0.9$. Plot the (sample) ACF and PACF for each of the three models and compare with their theoretic values. What do you find about their tailing behavior?


## Question 4

Consider a system process given by $$x_t=-.9x_{t-2}+w_t, \quad t=1,\cdots, n$$
where $x_0\sim N(0, \sigma^2_0)$, $x_{-1}\sim N(0, \sigma^2_1)$, and $w_t$ is Gaussian white noise with variance $\sigma^2_w$.
The system process is observed with noise: $$y_t=x_t+v_t,$$
where $v_t$ is Gaussian white noise with variance $\sigma^2_v$. Further, suppose $x_0$, $x_{-1}$, $\{w_t\}$ and $\{v_t\}$ are independent.

(a) Write the system and observation equations in the form of a state space model.
(b) Find the values of $\sigma^2_0$ and $\sigma^2_1$ that make the observations, $y_t$, stationary.
(c) Generate $n=100$ observations with $\sigma_w=1$, $\sigma_v=1$ and using the values of $\sigma^2_0$ and $\sigma^1_1$ found in (b). Do a time plot of $x_t$ and of $y_t$ and compare the two processes. Also, compare the sample ACF and PACF of $x_t$ and $y_t$.
(d) Repeat (c), but with $\sigma_v=10$.
