---
title: "STP598sta: Spatiotemporal Analysis"
subtitle: "Homework 1"
author: "Name: Your name; NetID: Your ID"
date: "Due 11:59pm Friday Sept 25 2020"
output:
  pdf_document: default
  # html_document: default
  # word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
options(width = 1000)
```

## Question 1

(a) Write a computer program using e.g. `R`, to computer the distance between 2 points $P_1$ and $P_2$ on the surface of the earth. The function should take the latitude and longitude of $P_i$ as in put, and output the geodesic distance $D$. Use the earth radius $R=6371$ km.

(b) Use your function to obtain the geodesic distances: (1) between Chicago (87.63W, 41.88N) and Minneapolis (93.22W, 44.89N), and (2) between New York (73.97W, 40.78N) and New Orleans (90.25W, 29.98N).


<!-- ## Question 2 -->

<!-- Consider the time series, $Y_t=X=\sin(\omega t+\theta)$ (so $X$ is the amplitude, $\omega$ is the frequency and $\theta$ is the phase) where $X$ is distributed with mean 0 and variance 1 independent of $\theta\sim \mathrm{unif}(-\pi, \pi)$). Show that $Y_t$ is weakly stationary. -->


## Question 2

The \emph{turning bands method} (Christakos, 1984; Stein, 1999a) is a technique for creating stationary covariance functions on $\mathbb R^r$. Let ${\bf u}$ be a random unit vector on $\mathbb R^r$ (by random we mean that the coordinate vector that defines ${\bf u}$ is randomly chosen on the surface of the unit sphere in $\mathbb R^r$). Let $c(\cdot)$ be a valid stationary covariance function on $\mathbb R^1$, and let $W(t)$ be a process on $\mathbb R^1$ having $c(\cdot)$ as its covariance function. Then for any location ${\bf s}\in\mathbb R^r$, define $$Y({\bf s})=W({\bf s}^T{\bf u}).$$ Note that we can think of the process either conditionally given ${\bf u}$, or marginally by integrating with respect to the uniform distribution for ${\bf u}$. Note also that $Y({\bf s})$ has the possibly undersirable property that it is constant on planes (i.e. on ${\bf s}^T{\bf u}=k$).

(a) If $W$ is a Gaussian process, show that, given ${\bf u}$, $Y({\bf s})$ is also a Gaussian process and is stationary.

(b) Show that marginally $Y({\bf s})$ is \emph{not} a Gaussian process, but is isotropic.
[Hint: Show that $\mathrm{Cov}(Y({\bf s},Y({\bf s'})=\mathrm{E}_{\bf u}c(({\bf s}-{\bf s'})^T{\bf u})$.]

## Question 3

Consider the `coalash` data frame in the `gstat` package in `R` and available from [here](https://www.counterpointstat.com/uploads/1/1/9/3/119383887/coal.ash.txt). 
This data comes from the Pittsburgh coal seam on the Robena Mine Property in Greene County, PA (Cressie, 1993, p. 32). 
This data frame contains 208 coal ash core samples (the variable coal in the data frame) collected on a grid given by $x$ and $y$ planar coordinates (\emph{not} latitude and longitude).

(a) Plot the sampled sites embedded on a map of the region. Add contour lines to the plot.

(b) Provide a descriptive summary (histograms, stems, quantiles, means, range, etc.) of the variable coal in the data frame.

(c) Plot variograms and correlograms of the response and comment on the need for spatial analysis here.

(d) If you think that there is need for spatial analysis, arrive at your best estimates of the range, nugget, and sill.

### Question 4

Under a proper CAR model for ${\bf Y}$, i.e., with $\Sigma_{\bf y} = D_w -\rho W$ , obtain the correlation and
covariance between $Y_i$ and $Y_j$ .

### Question 5

Consider the `Columbus` data, available from [here](https://www.counterpointstat.com/uploads/1/1/9/3/119383887/columbus.dat), taken from Anselin (1988, p. 189) and also available within the `spdep` `R` package (but with possi- bly different variable names). These data record crime information for 49 neighborhoods in Columbus, OH, during 1980. Variables measured include NEIG, the neighborhood id value (1–49); HOVAL, its mean housing value (in \$1,000); INC, its mean household income (in \$1,000); CRIME, its number of residential burglaries and vehicle thefts per thousand households; OPEN, a measure of the neighborhood’s open space; PLUMB, the percentage of housing units without plumbing; DISCBD, the neighborhood centroid’s distance from the central business district; $X$, an $x$-coordinate for the neighborhood centroid (in arbitrary digitizing units, not polygon coordinates); $Y$ , the same as $X$ for the $y$-coordinate; AREA, the neighborhood’s area; and PERIM, the perimeter of the polygon describing the neighborhood.

(a) Use `spdep` in `R` to construct adjacency matrices for the neighborhoods of Columbus based upon centroid distances less than

i. $25\%$ of the maximum intercentroidal distances;
ii. $75\%$ of the maximum intercentroidal distances.

(b) For each of the two spatial neighborhoods constructed above, use the `spautolm` function to fit SAR models with CRIME as the dependent variable, and HOVAL, INC, OPEN, PLUMB, and DISCBD as the covariates. Compare your results and interpret your parameter estimates in each case.

(c) Repeat part (b) for CAR models. Compare your estimates with those from the SAR model and interpret them.
