---
title: "STP598sta: Spatiotemporal Analysis"
subtitle: "Final Project"
author: "Name: Your name; NetID: Your ID"
date: "Due 11:59pm Tuesday December 8 2020"
output:
  pdf_document: default
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Final Project

Finish the project you planned in the midterm project plan. You are supposed to submit a final project report of data analysis using the techniques you learned from this class. It should involve spatial data, time series or spatiotemporal data. 

Choose a spatiotemporal data set and define a problem (or problems) you want to solve, e.g. regression, classification, prediction, etc.
Try to use the techniques you learned from the class. But do not be limited to them. Feel free to adopt machine learning/deep learning methods and make comparison.

For the final, you need to write a report of your data analysis which should includes:

- Data description;
- Problem(s) you plan to solve;
- Methodology;
- Scientific findings of your data analysis.

The report should be at least 3 pages. Submit it to canvas in pdf.

## Teamwork

You can form teams with your classmates. There are **1~2** members allowed for each team. It is suggested that you continue working with your team member for the midterm project plan. Only team leader needs to submit final report to canvas.

For submission:

- Submit only an `pdf` file.
- The pdf should clearly contain the **names** and **ASU ID** for each of your team member.

A nice candidate could be Covid-19 data set.
You can find datasets at [UCI machine learning data repository](http://archive.ics.uci.edu/ml/datasets.php).
More data resources can be found [here](https://github.com/slan-teaching/DAT301/blob/master/projects/Data%20Resources%20on%20Web.pdf).